### ISSUE TITLE
Xhud does not show anything anymore

### ISSUE THREAD

**Issue by DueKay** [PetteriM1/XHud#1]
Morgen PetteriM1
Ich benutze dieses Plugin jetzt schon ein bisschen länger und finde es richtig klasse, da es so simpel ist und bislang perfekt funktioniert hat.
Ich lasse mir in allen Welten damit die OnlineUser anzeigen und in der Plotwelt den eigenen Geldstand! Seid dem letzten Nukkit update (ist das einzige wodurch das ausgelösten worden siein konnte) sehe ich die Zeilen allerdings nicht mehr :(
Ich hoffe das du das einfach fixen kannst, da mir das Plugin mega gefällt und ich mir nur ungerne ein anderes suchen wollen würder.

Lg DueKay

___________________________________________________________________________________________________

Morning PetteriM1
I've been using this plugin for a while now and I think it's really great because it's so simple and has worked perfectly so far.
I let the online users show me in all worlds and their own money in the plot world! Be the last Nukkit update (the only thing that could have caused it to be triggered) I do not see the lines anymore though :(
I hope you can just fix it, because I really like the plugin and I would not like to search for another one.

Lg DueKay

**Comment by PetteriM1** [comment]
Haven't tested this with the latest build yet but I guess this https://github.com/NukkitX/Nukkit/commit/1ef05935f6fb25e581143b9a5484f2f698c1c68b could be the issue

**Comment by DueKay** [comment]
Can you adjust in your plugin what is going on again? :)
nukkit will think I will not do anything

**Comment by PetteriM1** [comment]
I created an issue to Nukkit, gotta see will they fix this

**Comment by PetteriM1** [comment]
Should be fixed in latest Nukkit builds
